---
- name: Add line to text file if it doesn't exist
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Add line to file in windows if it does not already exist
      win_copy:
        dest: "c:/NEW.txt"
        content: |
          line 01
          line 02
      when: ansible_system == 'Windows'
      
    - name: Add line to file in Linux/Unix if it does not already exist
      copy:
        dest: "c:/NEW.txt"
        content: |
          line 01
          line 02
      when: ansible_system != 'Windows'
